name: trace-workflows-action
description: Export a trace of GitHub Actions workflows to OpenTelemetry

inputs:
  token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
  enable-oltp-exporter:
    description: Enable OTLP exporter
    required: false
    default: 'false'
  oltp-endpoint:
    description: If set, export a trace to this endpoint
    required: false
    deprecationMessage: Use `enable-oltp-exporter` instead
  page-size-of-check-suites:
    description: Page size of CheckSuites query
    required: true
    default: '100'
  page-size-of-check-runs:
    description: Page size of CheckRuns query
    required: true
    default: '100'

runs:
  using: 'node20'
  main: 'dist/index.js'
