name: trace-workflows-action
description: Send a trace of GitHub Actions workflows to OpenTelemetry

inputs:
  token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
  oltp-endpoint:
    description: If set, emit a trace to the OpenTelemetry endpoint
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
