name: typescript-action-with-graphql-codegen
description: Template of TypeScript Action

inputs:
  sha:
    description: Target commit SHA
    required: true
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
  oltp-endpoint:
    description: If set, export traces. For example, http://localhost:4318/v1/traces
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
