name: typescript-action-with-graphql-codegen
description: Template of TypeScript Action

inputs:
  sha:
    description: Target commit SHA
    required: true
    default: ${{ github.sha }}
  token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
