name: trace-workflows-action
description: Send a trace of GitHub Actions workflows to OpenTelemetry

inputs:
  token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
  oltp-endpoint:
    description: If set, emit a trace to the OpenTelemetry endpoint
    required: false
  page-size-of-check-suites:
    description: Page size of CheckSuites query
    required: true
    default: '10'
  page-size-of-check-runs:
    description: Page size of CheckRuns query
    required: true
    default: '10'
  page-size-of-steps:
    description: Page size of Steps query
    required: true
    default: '50'

runs:
  using: 'node20'
  main: 'dist/index.js'
