# https://docs.datadoghq.com/opentelemetry/collector_exporter/configuration/
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 1s

exporters:
  datadog:
    api:
      key: ${env:DD_API_KEY}

connectors:
    datadog/connector:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/connector]
    traces/2:
      receivers: [datadog/connector]
      processors: [batch]
      exporters: [datadog]
