name: e2e-fixture-2

on:
  pull_request:

jobs:
  do:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        id: [4, 5]
    steps:
      - run: date
