name: e2e

on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed

jobs:
  test:
    name: test / ${{ github.event_name }} / ${{ github.event.action }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      checks: read
    steps:
      - name: Event
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            core.info(`eventName=${context.eventName}`)
            core.info(`sha=${context.sha}`)
            core.info(`ref=${context.ref}`)
            core.info(`actor=${context.actor}`)
            core.info(`payload=${JSON.stringify(context.payload, undefined, 2)}`)
      - uses: int128/trace-workflows-action@b2c32949262420bea11659721f6c6a19b568edba # v0
