name: e2e

on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed
  pull_request:
    paths:
      - .github/workflows/e2e.yaml

jobs:
  test:
    name: test / ${{ github.event_name }} / ${{ github.event.action }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      checks: read
    steps:
      - uses: int128/opentelemetry-collector-action@bff48cd69855003024ecfe5bba54bbbccfd4402d # v0.6.0
        with:
          readiness-probe-port: 13133
          environments: |
            DD_API_KEY=${{ secrets.DD_API_KEY }}
          config: |
            receivers:
              otlp:
                protocols:
                  http:
                    endpoint: 0.0.0.0:4318
            processors:
              batch:
            exporters:
              datadog:
                api:
                  key: ${env:DD_API_KEY}
            extensions:
              health_check:
                endpoint: 0.0.0.0:13133
            service:
              extensions: [health_check]
              pipelines:
                traces:
                  receivers: [otlp]
                  processors: [batch]
                  exporters: [datadog]

      - name: Event
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            core.info(`eventName=${context.eventName}`)
            core.info(`sha=${context.sha}`)
            core.info(`ref=${context.ref}`)
            core.info(`actor=${context.actor}`)
            core.info(`payload=${JSON.stringify(context.payload, undefined, 2)}`)
      - uses: int128/trace-workflows-action@c516a839629c9bfd86b908b41c57da86f0c8a9ae # v0.21.0
        with:
          oltp-endpoint: http://127.0.0.1:4318/v1/traces
