name: fixture

on:
  pull_request:

jobs:
  do:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        id: [1, 2, 3, 4, 5]
    steps:
      - run: date
